### PR TITLE
Created requirements file for audio and speech

### PR DESCRIPTION
**Pull request by MATRIX4284**
Created requirements file for audio and speech for ASR,Audio effects

### CODE REVIEW

**Comment by dciborow** [comment]
Hey, thanks for the contribution. In order to make these dependencies accessible you would need to add a entry in the extras dict in the setup.py.

**Comment by MATRIX4284** [comment]
Hi Daniel,

I will add it now. Thanks a lot for the suggestion.

*Thanks & Regards,*
*Kaustav*
*Technical Envagelist*
*Embedded & Distributed Systems*

**Comment by MATRIX4284** [comment]
Hi Daniel,

I have added the entry.
*Thanks & Regards,*
*Kaustav*
*Technical Envagelist*
*Embedded & Distributed Systems*

**Review by dciborow — APPROVED** [review]

**Review by raghavthind2005 — APPROVED** [review]

**Pull request merged**
